server:
  port: 8080
  servlet:
    context-path: /bootMybatis
    
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/usertest
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
    
mybatis:
  mapper-locations:
  - classpath:com.bootMybatis.mapper/*.xml
  type-aliases-package: com.bootMybatis.pojo
  
mapper:
  mappers:
  - com.bootMybatis.utils.MyMapper
  
